version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    commit-message:
      prefix: "ci"
    cooldown:
      default-days: 10
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    groups:
       actions:
          patterns:
            - "*"

  - directory: ".github/actions/launch-mapdl-docker"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown

  - directory: "/" # Location of package manifests
    package-ecosystem: "pip" # See documentation for possible values
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "build"
    cooldown:
      default-days: 10
      semver-patch-days: 3
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-tools-visualization-interface"
    exclude-paths:
      - "doc/source/examples/extended_examples/**"
    groups:
       minimal:
          patterns:
            - "ansys-api-mapdl"
            - "numpy"
            - "platformdirs"
            - "psutil"

       grpc-deps:
          patterns:
            - "google*"
            - "grpc*"
            - "protobuf"

       core:
          patterns:
            - "ansys*"
            - "click"
            - "matplotlib"
            - "pexpect"
            - "pyiges"
            - "ansys-tools-visualization-interface"
            - "scipy"
            - "tqdm"
            - "vtk"
            - "tabulate"

          exclude-patterns:
            - "ansys-api-mapdl"
            - "ansys-dpf-core"
            - "pyansys-tools-report"

       documentation:
          patterns:
            - "*sphinx*"
            - "ansys-dpf-core"
            - "imageio*"
            - "jupyter*"
            - "numpydoc"
            - "pandas"
            - "plotly"
            - "pypandoc"
            - "pythreejs"

       testing:
          patterns:
            - "autopep8"
            - "pytest*"
            - "pyansys-tools-report"

          exclude-patterns:
            - "ansys-dpf-core"

       jupyter:
          patterns:
            - "ipywidgets"
