version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    assignees:
      - "ansys/pymapdl-maintainers"
    commit-message:
      prefix: "ci"
    groups:
       actions:
          patterns:
            - "*"

  - directory: "/" # Location of package manifests
    package-ecosystem: "pip" # See documentation for possible values
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"      
      day: "friday"
      time: "00:00"
    labels:
      - "Maintenance"
      - "Dependencies"
    assignees:
      - "ansys/pymapdl-maintainers"
    commit-message:
      prefix: "build"
    groups:
       minimal:
          patterns:
            - "ansys-api-mapdl"
            - "importlib-metadata"
            - "numpy"
            - "platformdirs"
            - "psutil"
            - "pyansys-tools-versioning"

       grpc-deps:
          patterns:
            - "google*"
            - "grpc*"
            - "protobuf"

       core:
          patterns:
            - "*ansys*"
            - "click"
            - "matplotlib"
            - "pexpect"
            - "pyiges"
            - "pyvista"
            - "scipy"
            - "tqdm"
            - "vtk"

          exclude-patterns:
            - "ansys-api-mapdl"
            - "ansys-dpf-core"
            - "pyansys-tools-report"
            - "pyansys-tools-versioning"

       documentation:
          patterns:
            - "*sphinx*"
            - "ansys-dpf-core"
            - "imageio*"
            - "jupyter*"
            - "numpydoc"
            - "pandas"
            - "plotly"
            - "pypandoc"
            - "pythreejs"

       testing:
          patterns:
            - "autopep8"
            - "pytest*"
            - "pyansys-tools-report"

          exclude-patterns:
            - "ansys-dpf-core"

       jupyter:
          patterns:
            - "ipywidgets"
