# -*- coding: utf-8 -*-
# :Project:   pyansys -- Configuration to build and upload Windows wheels to PyPI
# :Author:    Alex Kaszynski <akascap@gmail.com>
# :License:   MIT License

# only build cp35, cp36, cp37 as vtk wheels is only offered in those versions
environment:
  CIBW_BEFORE_BUILD: "pip install numpy==1.15.0 cython"
  CIBW_TEST_REQUIRES: "pytest scipy matplotlib"
  CIBW_TEST_COMMAND: "pytest {project}\\tests -v"
  CIBW_SKIP: "*win32* cp27-* cp33* cp34*"
  TWINE_USERNAME: akaszynski
  # Note: TWINE_PASSWORD is set in Appveyor settings
  matrix:
    - PYTHON: "C:\\Python35-x64\\python.exe"


install:
  # configure a headless display
  - "git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"
  - "SET PYVISTA_OFF_SCREEN=True"
  - pip install twine  # for upload


build_script:
  - "%PYTHON% -m pip install cibuildwheel"
  - "%PYTHON% -m cibuildwheel --output-dir wheelhouse"
  - "%PYTHON% -m pip install twine"
  - "%PYTHON% -m twine upload wheelhouse/*.whl --skip-existing"
  # - >
  #   IF "%APPVEYOR_REPO_TAG%" == "true"
  #   (
  #   python -m pip install twine
  #   &&
  #   python -m twine upload wheelhouse/*.whl --skip-existing
  #   )

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels