version: '3.3'

# DESCRIPTION
# ===========
#
# This docker-compose file extends the 'base' docker-compose file by adding a license server.
# The usage of the license server is discouraged.
#
# In this docker-compose file, the service is faking to be this hostname, by faking the hostname and MAC address.
# Then, we mount the local 'licenses' directory into the container, so that the container can use the license file.
#
#
# USAGE
# =====
#
# 1. You need to have a license file for the license server. This file should be named 'license.lic' and
# should be located in a folder called 'licenses'.
#
# 2. Because the license file is specific to a hostname, you need to create a environment variable called
# 'LICENSE_SERVER_HOSTNAME' and set it to the hostname of the license server. For example:
#
#      export LICENSE_SERVER_HOSTNAME=mylicenseserver
#
# 3. The license file is also expecific to a MAC address, therefore you need to create another environment
# variable called 'LICENSE_SERVER_MAC_ADDRESS' and set it to the MAC address of the license server. For example:
#
#      export LICENSE_SERVER_MAC_ADDRESS=00:00:00:00:00:00
#
# 4. Once you have done this, you can start the license server by running:
#
#      docker-compose -f docker-compose.yml -f docker-compose.license-server.yml up
#

services:
  license_server:
    image: 'ghcr.io/ansys/ansyslm:222'
    ports:
      - '1055:1055'
      - '2325:2325'
      - '6000:6000'
      - '1084:1084'
    restart: always
    volumes:
      - ../licenses:/ansyslm/shared_files/licensing/license_files:cached
    hostname: ${LICENSE_SERVER_HOSTNAME}
    container_name: license_server
    mac_address: ${LICENSE_SERVER_MAC_ADDRESS}
    environment:
      - LM_LICENSE_FILE=/ansyslm/shared_files/licensing/license_files/license.lic

  # Overwrite the license environment variable to point to the created license server
  mapdl:
    environment:
      - ANSYSLMD_LICENSE_FILE=1055@${LICENSE_SERVER_HOSTNAME}

  dpf:
    environment:
      - ANSYSLMD_LICENSE_FILE=1055@${LICENSE_SERVER_HOSTNAME}