name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: [ main ]
    paths:
      - '../labels.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  label-syncer:
    # Sync the labels name, colours with the file ``labels.yml``
    name: Syncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Set labels
    needs: [label-syncer]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

    # Label based on modified files
    - name: Label based on changed files
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: ''

    # Label based on branch name
    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'doc') || 
        startsWith(github.event.pull_request.head.ref, 'docs')
      with:
        labels: Documentation

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'docker') ||
        startsWith(github.event.pull_request.head.ref, 'no-ci') ||
        startsWith(github.event.pull_request.head.ref, 'ci')
      with:
        labels: CI/CD

    - uses: actions-ecosystem/action-add-labels@v1
      if: startsWith(github.event.pull_request.head.ref, 'maint')
      with:
        labels: Maintenance

    - uses: actions-ecosystem/action-add-labels@v1
      if: startsWith(github.event.pull_request.head.ref, 'feat')
      with:
        labels: |
          Enhancement
          NEW FEATURE

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'fix') ||
        startsWith(github.event.pull_request.head.ref, 'patch')
      with:
        labels: BUG

  commenter:
    runs-on: ubuntu-latest
    needs: [labeler]
    permissions:
      pull-requests: write
    steps:
    - name: Suggest to add labels
      uses: peter-evans/create-or-update-comment@v3
      # Execute only when no labels have been applied to the pull request
      # if: toJSON(github.event.pull_request.labels.*.name) == '[]'
      if: toJSON(github.event.pull_request.labels.*.name) == '{}' # Empty labels
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Please add one of the following labels to add this contribution to the Release Notes :point_down:
          - [BUG](https://github.com/ansys/pymapdl/pulls?q=label%3Abug+)
          - [NEW FEATURE](https://github.com/ansys/pymapdl/pulls?q=label%3A"NEW%20FEATURE"+)
          - [Enhancement](https://github.com/ansys/pymapdl/pulls?q=label%3Aenhancement+)
          - [Documentation](https://github.com/ansys/pymapdl/pulls?q=label%3Adocumentation+)
          - [Examples](https://github.com/ansys/pymapdl/pulls?q=label%3Aexamples+)
          - [Maintenance](https://github.com/ansys/pymapdl/pulls?q=label%3Amaintenance+)
          - [CI/CD](https://github.com/ansys/pymapdl/pulls?q=label%3Aci%2Fcd+)
